# PyTorch의 구성요소
* torch: Tensor를 생성
* torch.autograd: 자동 미분 기능
* torch.nn: 신경망 생성
* torch.multiprocessing: 병렬처리 가능

## torch.Tensor 만들기
* torch.empty: 값이 저장된 상태를 보여줌
* torch.zeros: 값이 0으로 초기화 된 것을 보여줌
* torch.rand(): 0~1사이의 숫자 중, 랜덤으로 지정

In [2]:
import torch

x = torch.empty(3)
print(x)

tensor([0., 0., 0.])


In [5]:

x = torch.rand(2, 4)
print(x)

tensor([[0.4063, 0.7747, 0.5049, 0.5344],
        [0.8644, 0.1687, 0.4077, 0.1318]])


In [6]:
y = torch.zeros(2, 4, dtype=torch.long)
print(y)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])


In [7]:
z = torch.tensor([[2, 3, 4], [5, 1, 2]])
print(z)

tensor([[2, 3, 4],
        [5, 1, 2]])


In [9]:
# 주어진 값과 똑같은 모양으로 출력
# 단, 값들은 랜덤하게 저장
y = torch.randn_like(x, dtype=torch.float)
print(y)
print(x)

tensor([[-0.8306, -1.6305,  0.1078,  0.9075],
        [ 0.5987, -1.6085,  1.7917, -0.0118]])
tensor([[0.4063, 0.7747, 0.5049, 0.5344],
        [0.8644, 0.1687, 0.4077, 0.1318]])


In [12]:
print(z)
print(z.new_ones(1, 3, dtype=torch.double))

tensor([[2, 3, 4],
        [5, 1, 2]])
tensor([[1., 1., 1.]], dtype=torch.float64)
tensor([[2, 3, 4],
        [5, 1, 2]])


## torch.Tensor 조작하기

In [16]:
print(x)
print(x.size())

tensor([[0.4063, 0.7747, 0.5049, 0.5344],
        [0.8644, 0.1687, 0.4077, 0.1318]])
torch.Size([2, 4])


In [18]:
# view를 사용해서 Tensor의 차원 변경 기능
x = torch.randn(4, 5)
y = x.view(20)
z = x.view(5, -1)

print(x.size())
print(y.size())
print(z.size())

torch.Size([4, 5])
torch.Size([20])
torch.Size([5, 4])


In [20]:
print(x)
print(x.dtype)

tensor([[-0.1347, -0.5035, -0.8150,  0.1879, -0.3867],
        [ 0.3670, -0.5448, -0.7411, -2.6504,  0.1852],
        [-0.3172,  2.3775,  0.8065,  2.6391,  0.1513],
        [-0.0320, -0.0627, -1.1219,  0.6784,  1.3605]])
torch.float32


In [23]:
print(x)
print(x[0, 0]) # 숫자가 아닌, Tensor클래스의 객체가 출력
print(x[1, 1])
print(x[0, 0].item())

tensor([[-0.1347, -0.5035, -0.8150,  0.1879, -0.3867],
        [ 0.3670, -0.5448, -0.7411, -2.6504,  0.1852],
        [-0.3172,  2.3775,  0.8065,  2.6391,  0.1513],
        [-0.0320, -0.0627, -1.1219,  0.6784,  1.3605]])
tensor(-0.1347)
tensor(-0.5448)
-0.1346590369939804


In [26]:
print(x[:, 1])
print(x[1, :])
print(x[0:2])
print(x[:,0:2])

tensor([-0.5035, -0.5448,  2.3775, -0.0627])
tensor([ 0.3670, -0.5448, -0.7411, -2.6504,  0.1852])
tensor([[-0.1347, -0.5035, -0.8150,  0.1879, -0.3867],
        [ 0.3670, -0.5448, -0.7411, -2.6504,  0.1852]])
tensor([[-0.1347, -0.5035],
        [ 0.3670, -0.5448],
        [-0.3172,  2.3775],
        [-0.0320, -0.0627]])


## torch.Tensor 연산하기

In [28]:
print(x)
print(x+1)
print(x*2)
print(x/2)

tensor([[-0.1347, -0.5035, -0.8150,  0.1879, -0.3867],
        [ 0.3670, -0.5448, -0.7411, -2.6504,  0.1852],
        [-0.3172,  2.3775,  0.8065,  2.6391,  0.1513],
        [-0.0320, -0.0627, -1.1219,  0.6784,  1.3605]])
tensor([[ 0.8653,  0.4965,  0.1850,  1.1879,  0.6133],
        [ 1.3670,  0.4552,  0.2589, -1.6504,  1.1852],
        [ 0.6828,  3.3775,  1.8065,  3.6391,  1.1513],
        [ 0.9680,  0.9373, -0.1219,  1.6784,  2.3605]])
tensor([[-0.2693, -1.0070, -1.6301,  0.3758, -0.7734],
        [ 0.7341, -1.0895, -1.4822, -5.3007,  0.3704],
        [-0.6345,  4.7550,  1.6130,  5.2782,  0.3025],
        [-0.0641, -0.1255, -2.2438,  1.3567,  2.7210]])
tensor([[-0.0673, -0.2517, -0.4075,  0.0940, -0.1934],
        [ 0.1835, -0.2724, -0.3706, -1.3252,  0.0926],
        [-0.1586,  1.1888,  0.4032,  1.3196,  0.0756],
        [-0.0160, -0.0314, -0.5609,  0.3392,  0.6802]])


### Matrix Multiplication

In [34]:
x = torch.randn(2, 4)
y = torch.randn(2, 4)
print(x)
print(y)

tensor([[-0.6996,  0.0800,  0.2717,  0.7361],
        [ 1.7452, -0.0989,  0.5218,  0.9180]])
tensor([[ 0.9020,  0.3617,  0.0980, -0.5431],
        [ 1.7903,  0.1090,  0.9525,  1.5028]])


In [35]:
print(torch.mm(x, y))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x4 and 2x4)

In [36]:
print(torch.mm(x, y.T))

tensor([[-0.9753,  0.1211],
        [ 1.0909,  4.9903]])


## torch <-> numpy

In [37]:
x = torch.ones(7)
y = x.numpy()

print(x) # PyTorch의 Tensor클래스 객체
print(y) # NumPy의 Ndarray 객체

tensor([1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1.]


In [40]:
import numpy as np

z = np.arange(12).reshape(4, 3)
print(z)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [42]:
q = torch.from_numpy(z)
print(q)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
