# ndarray multidimension

## 1차원

In [2]:
import numpy as np

a = np.arange(0, 40)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

## 2차원
* reshape: 데이터 차원과 모양 변경

In [6]:
b = a.reshape(2, 20)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39]])

## 3차원

In [5]:
c = a.reshape(4, 2, 5)
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

## 4차원

In [9]:
d = a.reshape(2, 2, 2, 5)
d

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]],


       [[[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]]])

In [10]:
e = a.reshape(5, 2, 2, 2)
e

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27]],

        [[28, 29],
         [30, 31]]],


       [[[32, 33],
         [34, 35]],

        [[36, 37],
         [38, 39]]]])

# 연산


In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]])

a.sum()

np.int64(21)

In [12]:
a.sum(axis=0)

array([5, 7, 9])

In [13]:
a.sum(axis=1)

array([ 6, 15])

* min: 최솟값
* max: 최댓값
* argmin/max: 최솟값/최댓값을 가진 원소의 인덱스