In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
type(a)

numpy.ndarray

In [2]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 4, 5])

print(a + b)

[ 2  4  6  8 10]


## Indexing and dtype

In [3]:
a[0]

np.int64(1)

In [4]:
a[1]

np.int64(2)

In [6]:
a[0] = 10
a

array([10,  2,  3,  4,  5])

In [7]:
a.dtype

dtype('int64')

In [10]:
a[0] = 10.6
a

array([10,  2,  3,  4,  5])

In [13]:
a.fill(-4.8)
a

array([-4, -4, -4, -4, -4])

## 2d ndarray

In [14]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### shape: 배열의 형태를 튜플로 반환

In [15]:
a.shape

(2, 4)

### size: 전체 원소의 개수

In [16]:
a.size

8

### ndim: 배열의 차원

In [17]:
a.ndim

2

## Advanced Indexing

In [19]:
a = np.arange(0, 80, 10)
b = [1, 2, -3]
a[b] = 100
a

array([  0, 100, 100,  30,  40, 100,  60,  70])

In [21]:
a = np.arange(0, 80, 10)
b = np.array([0, 1, 1, 0, 0, 1, 0, 0], dtype=bool)
a[b]

array([10, 20, 50])