# Scalars
* 숫자 한 개 - rank 0

In [1]:
import numpy as np

x = np.array(3.0)
y = np.array(2.0)

print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)
print(x**y)

5.0
1.0
6.0
1.5
1.0
9.0


# Vectors
* 숫자 여러 개 - rank 1
* 차원 = vector의 숫자 개수

In [2]:
import numpy as np

x = np.arange(10)

print(len(x))
print(x.shape)

10
(10,)


# Matrices
* 행과 열로 이루어진 숫자 - rank 2

In [5]:
a = np.arange(20).reshape(5, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


## transpose: 행과 열 바꾸기, 전치

In [6]:
print(a.T)

[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


## Symmetric Matrix (대칭행렬)
$A = A^T$

In [7]:
b = np.array([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
print(b)

[[1 2 3]
 [2 0 4]
 [3 4 5]]


In [9]:
print(b == b.T)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Matrix Multiplication (행렬 곱)
* dot: 벡터 내적, 행렬곱 함수

In [14]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 0], [0, 1]])

print(a)
print(b)
print(np.dot(a, b))

[[1 2]
 [3 4]]
[[1 0]
 [0 1]]
[[1 2]
 [3 4]]
