# Tensor
Rank 3 이상의 숫자

In [1]:
import numpy as np

x = np.arange(24).reshape(2,3,4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## einsum:
np.einsum('index', ndarray)
특정 index의 집합에 대한 합 연산을 간결하게 표시하는 방법

In [5]:
a = np.arange(60).reshape(3, 4, 5)
b = np.arange(24).reshape(4, 3, 2)
np.einsum('ijk,jil->kl', a, b)

array([[4400, 4730],
       [4532, 4874],
       [4664, 5018],
       [4796, 5162],
       [4928, 5306]])